[2023-03-08T22:01:37.059+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.chatgpt_prediction manual__2023-03-08T21:23:11.089498+00:00 [queued]>
[2023-03-08T22:01:37.098+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.chatgpt_prediction manual__2023-03-08T21:23:11.089498+00:00 [queued]>
[2023-03-08T22:01:37.101+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T22:01:37.116+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-03-08T22:01:37.119+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T22:01:37.163+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonVirtualenvOperator): chatgpt_prediction> on 2023-03-08 21:23:11.089498+00:00
[2023-03-08T22:01:37.191+0000] {standard_task_runner.py:55} INFO - Started process 2197 to run task
[2023-03-08T22:01:37.221+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_second_webscrape', 'chatgpt_prediction', 'manual__2023-03-08T21:23:11.089498+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmplftfi025']
[2023-03-08T22:01:37.232+0000] {standard_task_runner.py:83} INFO - Job 255: Subtask chatgpt_prediction
[2023-03-08T22:01:37.501+0000] {task_command.py:388} INFO - Running <TaskInstance: bitcoin_second_webscrape.chatgpt_prediction manual__2023-03-08T21:23:11.089498+00:00 [queued]> on host cd114ba8c1f8
[2023-03-08T22:01:37.944+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin_second_webscrape
AIRFLOW_CTX_TASK_ID=chatgpt_prediction
AIRFLOW_CTX_EXECUTION_DATE=2023-03-08T21:23:11.089498+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-08T21:23:11.089498+00:00
[2023-03-08T22:01:37.999+0000] {process_utils.py:179} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv9w_pi8vr --system-site-packages
[2023-03-08T22:01:38.117+0000] {process_utils.py:183} INFO - Output:
[2023-03-08T22:01:39.796+0000] {process_utils.py:187} INFO - created virtual environment CPython3.7.16.final.0-64 in 574ms
[2023-03-08T22:01:39.800+0000] {process_utils.py:187} INFO -   creator CPython3Posix(dest=/tmp/venv9w_pi8vr, clear=False, no_vcs_ignore=False, global=True)
[2023-03-08T22:01:39.802+0000] {process_utils.py:187} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-03-08T22:01:39.805+0000] {process_utils.py:187} INFO -     added seed packages: pip==23.0.1, setuptools==67.2.0, wheel==0.38.4
[2023-03-08T22:01:39.807+0000] {process_utils.py:187} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-03-08T22:01:39.831+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venv9w_pi8vr/bin/pip install -r /tmp/venv9w_pi8vr/requirements.txt
[2023-03-08T22:01:39.853+0000] {process_utils.py:183} INFO - Output:
[2023-03-08T22:01:40.991+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.chatgpt_prediction manual__2023-03-08T21:23:11.089498+00:00 [queued]>
[2023-03-08T22:01:41.037+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.chatgpt_prediction manual__2023-03-08T21:23:11.089498+00:00 [queued]>
[2023-03-08T22:01:41.040+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T22:01:41.042+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-03-08T22:01:41.045+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T22:01:41.119+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonVirtualenvOperator): chatgpt_prediction> on 2023-03-08 21:23:11.089498+00:00
[2023-03-08T22:01:41.147+0000] {standard_task_runner.py:55} INFO - Started process 2209 to run task
[2023-03-08T22:01:41.173+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_second_webscrape', 'chatgpt_prediction', 'manual__2023-03-08T21:23:11.089498+00:00', '--job-id', '256', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpy6g6bw4d']
[2023-03-08T22:01:41.176+0000] {standard_task_runner.py:83} INFO - Job 256: Subtask chatgpt_prediction
[2023-03-08T22:01:41.450+0000] {task_command.py:388} INFO - Running <TaskInstance: bitcoin_second_webscrape.chatgpt_prediction manual__2023-03-08T21:23:11.089498+00:00 [running]> on host cd114ba8c1f8
[2023-03-08T22:01:41.721+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin_second_webscrape
AIRFLOW_CTX_TASK_ID=chatgpt_prediction
AIRFLOW_CTX_EXECUTION_DATE=2023-03-08T21:23:11.089498+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-08T21:23:11.089498+00:00
[2023-03-08T22:01:41.735+0000] {process_utils.py:179} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvw54ge8uv --system-site-packages
[2023-03-08T22:01:41.790+0000] {process_utils.py:183} INFO - Output:
[2023-03-08T22:01:42.350+0000] {local_task_job.py:256} WARNING - Recorded pid 2209 does not match the current pid 2197
[2023-03-08T22:01:42.387+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 2197. PIDs of all processes in the group: [2206, 2197]
[2023-03-08T22:01:42.401+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 2197
[2023-03-08T22:01:42.404+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-08T22:01:42.425+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2206, status='terminated', started='22:01:39') (2206) terminated with exit code None
[2023-03-08T22:01:42.619+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 356, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 549, in execute_callable
    pip_install_options=self.pip_install_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/python_virtualenv.py", line 99, in prepare_virtualenv
    execute_in_subprocess(pip_cmd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 168, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/process_utils.py", line 186, in execute_in_subprocess_with_kwargs
    for line in iter(proc.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1481, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-03-08T22:01:42.637+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bitcoin_second_webscrape, task_id=chatgpt_prediction, execution_date=20230308T212311, start_date=20230308T220140, end_date=20230308T220142
[2023-03-08T22:01:42.691+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 255 for task chatgpt_prediction (Task received SIGTERM signal; 2197)
[2023-03-08T22:01:42.732+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2197, status='terminated', exitcode=1, started='22:01:36') (2197) terminated with exit code 1
[2023-03-08T22:01:43.733+0000] {process_utils.py:187} INFO - created virtual environment CPython3.7.16.final.0-64 in 798ms
[2023-03-08T22:01:43.738+0000] {process_utils.py:187} INFO -   creator CPython3Posix(dest=/tmp/venvw54ge8uv, clear=False, no_vcs_ignore=False, global=True)
[2023-03-08T22:01:43.740+0000] {process_utils.py:187} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-03-08T22:01:43.743+0000] {process_utils.py:187} INFO -     added seed packages: pip==23.0.1, setuptools==67.2.0, wheel==0.38.4
[2023-03-08T22:01:43.745+0000] {process_utils.py:187} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-03-08T22:01:43.768+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venvw54ge8uv/bin/pip install -r /tmp/venvw54ge8uv/requirements.txt
[2023-03-08T22:01:43.796+0000] {process_utils.py:183} INFO - Output:
[2023-03-08T22:01:47.306+0000] {process_utils.py:187} INFO - Collecting selenium
[2023-03-08T22:01:47.347+0000] {process_utils.py:187} INFO -   Using cached selenium-4.8.2-py3-none-any.whl (6.9 MB)
[2023-03-08T22:01:47.445+0000] {process_utils.py:187} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venvw54ge8uv/requirements.txt (line 2)) (1.3.5)
[2023-03-08T22:01:47.543+0000] {process_utils.py:187} INFO - Collecting gcsfs
[2023-03-08T22:01:47.549+0000] {process_utils.py:187} INFO -   Using cached gcsfs-2023.1.0-py2.py3-none-any.whl (26 kB)
[2023-03-08T22:01:47.554+0000] {process_utils.py:187} INFO - Requirement already satisfied: fsspec in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venvw54ge8uv/requirements.txt (line 4)) (2022.11.0)
[2023-03-08T22:01:47.556+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-storage in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venvw54ge8uv/requirements.txt (line 5)) (2.7.0)
[2023-03-08T22:01:47.558+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-bigquery in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venvw54ge8uv/requirements.txt (line 6)) (2.34.4)
[2023-03-08T22:01:47.560+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-auth in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venvw54ge8uv/requirements.txt (line 7)) (2.16.0)
[2023-03-08T22:01:47.562+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***-providers-google in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venvw54ge8uv/requirements.txt (line 8)) (8.8.0)
[2023-03-08T22:01:47.566+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***[google] in /home/***/.local/lib/python3.7/site-packages (from -r /tmp/venvw54ge8uv/requirements.txt (line 9)) (2.5.1)
[2023-03-08T22:01:47.647+0000] {process_utils.py:187} INFO - Collecting openai
[2023-03-08T22:01:47.650+0000] {process_utils.py:187} INFO -   Using cached openai-0.27.1-py3-none-any.whl
[2023-03-08T22:01:47.757+0000] {process_utils.py:187} INFO - Collecting trio~=0.17
[2023-03-08T22:01:47.765+0000] {process_utils.py:187} INFO -   Using cached trio-0.22.0-py3-none-any.whl (384 kB)
[2023-03-08T22:01:47.782+0000] {process_utils.py:187} INFO - Requirement already satisfied: certifi>=2021.10.8 in /home/***/.local/lib/python3.7/site-packages (from selenium->-r /tmp/venvw54ge8uv/requirements.txt (line 1)) (2022.12.7)
[2023-03-08T22:01:47.787+0000] {process_utils.py:187} INFO - Requirement already satisfied: urllib3[socks]~=1.26 in /home/***/.local/lib/python3.7/site-packages (from selenium->-r /tmp/venvw54ge8uv/requirements.txt (line 1)) (1.26.14)
[2023-03-08T22:01:47.850+0000] {process_utils.py:187} INFO - Collecting trio-websocket~=0.9
[2023-03-08T22:01:47.859+0000] {process_utils.py:187} INFO -   Using cached trio_websocket-0.9.2-py3-none-any.whl (16 kB)
[2023-03-08T22:01:47.903+0000] {process_utils.py:187} INFO - Requirement already satisfied: numpy>=1.17.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r /tmp/venvw54ge8uv/requirements.txt (line 2)) (1.21.1)
[2023-03-08T22:01:47.907+0000] {process_utils.py:187} INFO - Requirement already satisfied: python-dateutil>=2.7.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r /tmp/venvw54ge8uv/requirements.txt (line 2)) (2.8.2)
[2023-03-08T22:01:47.909+0000] {process_utils.py:187} INFO - Requirement already satisfied: pytz>=2017.3 in /home/***/.local/lib/python3.7/site-packages (from pandas->-r /tmp/venvw54ge8uv/requirements.txt (line 2)) (2022.7.1)
[2023-03-08T22:01:48.026+0000] {process_utils.py:187} INFO - Collecting fsspec
[2023-03-08T22:01:48.034+0000] {process_utils.py:187} INFO -   Using cached fsspec-2023.1.0-py3-none-any.whl (143 kB)
[2023-03-08T22:01:48.042+0000] {process_utils.py:187} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.7/site-packages (from gcsfs->-r /tmp/venvw54ge8uv/requirements.txt (line 3)) (2.28.2)
[2023-03-08T22:01:48.046+0000] {process_utils.py:187} INFO - Requirement already satisfied: decorator>4.1.2 in /home/***/.local/lib/python3.7/site-packages (from gcsfs->-r /tmp/venvw54ge8uv/requirements.txt (line 3)) (5.1.1)
[2023-03-08T22:01:48.050+0000] {process_utils.py:187} INFO - Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/***/.local/lib/python3.7/site-packages (from gcsfs->-r /tmp/venvw54ge8uv/requirements.txt (line 3)) (3.8.3)
[2023-03-08T22:01:48.053+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-auth-oauthlib in /home/***/.local/lib/python3.7/site-packages (from gcsfs->-r /tmp/venvw54ge8uv/requirements.txt (line 3)) (0.8.0)
[2023-03-08T22:01:48.149+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-storage->-r /tmp/venvw54ge8uv/requirements.txt (line 5)) (2.3.2)
[2023-03-08T22:01:48.153+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-resumable-media>=2.3.2 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-storage->-r /tmp/venvw54ge8uv/requirements.txt (line 5)) (2.4.0)
[2023-03-08T22:01:48.159+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-storage->-r /tmp/venvw54ge8uv/requirements.txt (line 5)) (2.8.2)
[2023-03-08T22:01:48.262+0000] {process_utils.py:187} INFO - Requirement already satisfied: packaging<22.0dev,>=14.3 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-bigquery->-r /tmp/venvw54ge8uv/requirements.txt (line 6)) (21.3)
[2023-03-08T22:01:48.265+0000] {process_utils.py:187} INFO - Requirement already satisfied: proto-plus<2.0.0dev,>=1.15.0 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-bigquery->-r /tmp/venvw54ge8uv/requirements.txt (line 6)) (1.19.6)
[2023-03-08T22:01:48.272+0000] {process_utils.py:187} INFO - Requirement already satisfied: grpcio<2.0dev,>=1.38.1 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-bigquery->-r /tmp/venvw54ge8uv/requirements.txt (line 6)) (1.51.1)
[2023-03-08T22:01:48.276+0000] {process_utils.py:187} INFO - Requirement already satisfied: protobuf<4.0.0dev,>=3.12.0 in /home/***/.local/lib/python3.7/site-packages (from google-cloud-bigquery->-r /tmp/venvw54ge8uv/requirements.txt (line 6)) (3.20.0)
[2023-03-08T22:01:48.353+0000] {process_utils.py:187} INFO - Requirement already satisfied: six>=1.9.0 in /home/***/.local/lib/python3.7/site-packages (from google-auth->-r /tmp/venvw54ge8uv/requirements.txt (line 7)) (1.16.0)
[2023-03-08T22:01:48.355+0000] {process_utils.py:187} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from google-auth->-r /tmp/venvw54ge8uv/requirements.txt (line 7)) (4.2.2)
[2023-03-08T22:01:48.360+0000] {process_utils.py:187} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.7/site-packages (from google-auth->-r /tmp/venvw54ge8uv/requirements.txt (line 7)) (4.9)
[2023-03-08T22:01:48.364+0000] {process_utils.py:187} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.7/site-packages (from google-auth->-r /tmp/venvw54ge8uv/requirements.txt (line 7)) (0.2.8)
[2023-03-08T22:01:48.516+0000] {process_utils.py:187} INFO - Requirement already satisfied: sqlalchemy-bigquery>=1.2.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.5.0)
[2023-03-08T22:01:48.518+0000] {process_utils.py:187} INFO - Requirement already satisfied: asgiref>=3.5.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (3.6.0)
[2023-03-08T22:01:48.520+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-pubsub>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (2.13.5)
[2023-03-08T22:01:48.523+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-translate<2.0.0,>=1.5.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.7.2)
[2023-03-08T22:01:48.525+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-container<3.0.0,>=2.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (2.11.1)
[2023-03-08T22:01:48.528+0000] {process_utils.py:187} INFO - Requirement already satisfied: gcloud-aio-bigquery>=6.1.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (6.2.0)
[2023-03-08T22:01:48.531+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-ads>=15.1.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (18.0.0)
[2023-03-08T22:01:48.533+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-api-python-client<2.0.0,>=1.6.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.12.11)
[2023-03-08T22:01:48.535+0000] {process_utils.py:187} INFO - Requirement already satisfied: httpx in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (0.23.3)
[2023-03-08T22:01:48.537+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dataproc>=3.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (5.0.0)
[2023-03-08T22:01:48.540+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-bigquery-datatransfer>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (3.7.0)
[2023-03-08T22:01:48.542+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-kms>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (2.12.0)
[2023-03-08T22:01:48.544+0000] {process_utils.py:187} INFO - Requirement already satisfied: json-merge-patch>=0.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (0.2)
[2023-03-08T22:01:48.546+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-vision<2.0.0,>=0.35.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.0.2)
[2023-03-08T22:01:48.548+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-texttospeech<2.0.0,>=0.4.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.0.3)
[2023-03-08T22:01:48.552+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dataproc-metastore<2.0.0,>=1.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.6.0)
[2023-03-08T22:01:48.555+0000] {process_utils.py:187} INFO - Requirement already satisfied: gcloud-aio-storage in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (8.0.0)
[2023-03-08T22:01:48.557+0000] {process_utils.py:187} INFO - Requirement already satisfied: gcloud-aio-auth>=4.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (4.1.5)
[2023-03-08T22:01:48.558+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-language<2.0.0,>=1.1.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.3.2)
[2023-03-08T22:01:48.560+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-aiplatform<2.0.0,>=1.7.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.16.1)
[2023-03-08T22:01:48.562+0000] {process_utils.py:187} INFO - Requirement already satisfied: grpcio-gcp>=0.2.2 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (0.2.2)
[2023-03-08T22:01:48.565+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-bigtable<2.0.0,>=1.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.7.3)
[2023-03-08T22:01:48.567+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-logging>=2.1.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (3.2.1)
[2023-03-08T22:01:48.571+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-compute<2.0.0,>=0.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (0.7.0)
[2023-03-08T22:01:48.573+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-speech<2.0.0,>=0.36.3 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.3.4)
[2023-03-08T22:01:48.576+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-workflows<2.0.0,>=0.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.7.1)
[2023-03-08T22:01:48.577+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-datacatalog>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (3.9.0)
[2023-03-08T22:01:48.579+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dataplex>=0.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.1.0)
[2023-03-08T22:01:48.582+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-tasks>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (2.10.1)
[2023-03-08T22:01:48.586+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-videointelligence<2.0.0,>=1.7.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.16.3)
[2023-03-08T22:01:48.589+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dataform>=0.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (0.2.0)
[2023-03-08T22:01:48.593+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-redis>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (2.9.0)
[2023-03-08T22:01:48.595+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-monitoring>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (2.11.0)
[2023-03-08T22:01:48.598+0000] {process_utils.py:187} INFO - Requirement already satisfied: apache-***-providers-common-sql>=1.3.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.3.3)
[2023-03-08T22:01:48.601+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-automl>=2.1.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (2.8.0)
[2023-03-08T22:01:48.604+0000] {process_utils.py:187} INFO - Requirement already satisfied: looker-sdk>=22.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (22.20.0)
[2023-03-08T22:01:48.606+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-orchestration-***<2.0.0,>=1.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.4.1)
[2023-03-08T22:01:48.608+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-memcache>=0.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.4.1)
[2023-03-08T22:01:48.610+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-secret-manager<2.0.0,>=0.2.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.0.2)
[2023-03-08T22:01:48.612+0000] {process_utils.py:187} INFO - Requirement already satisfied: PyOpenSSL in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (22.1.0)
[2023-03-08T22:01:48.614+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-dlp<2.0.0,>=0.11.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.0.2)
[2023-03-08T22:01:48.616+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-spanner<2.0.0,>=1.10.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (1.19.3)
[2023-03-08T22:01:48.619+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-os-login>=2.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (2.7.1)
[2023-03-08T22:01:48.620+0000] {process_utils.py:187} INFO - Requirement already satisfied: pandas-gbq in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (0.17.9)
[2023-03-08T22:01:48.623+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-auth-httplib2>=0.0.1 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (0.1.0)
[2023-03-08T22:01:48.627+0000] {process_utils.py:187} INFO - Requirement already satisfied: google-cloud-build>=3.0.0 in /home/***/.local/lib/python3.7/site-packages (from apache-***-providers-google->-r /tmp/venvw54ge8uv/requirements.txt (line 8)) (3.9.0)
[2023-03-08T22:01:51.308+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-08T22:01:51.321+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 2209. PIDs of all processes in the group: [2217, 2209]
[2023-03-08T22:01:51.324+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 2209
[2023-03-08T22:01:51.326+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-08T22:01:51.542+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2209, status='terminated', exitcode=0, started='22:01:40') (2209) terminated with exit code 0
[2023-03-08T22:01:51.546+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2217, status='terminated', started='22:01:43') (2217) terminated with exit code None
