[2023-03-08T16:57:00.040+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.chatgpt_prediction scheduled__2023-03-07T13:00:00+00:00 [queued]>
[2023-03-08T16:57:00.056+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_second_webscrape.chatgpt_prediction scheduled__2023-03-07T13:00:00+00:00 [queued]>
[2023-03-08T16:57:00.057+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T16:57:00.059+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-08T16:57:00.061+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T16:57:00.089+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): chatgpt_prediction> on 2023-03-07 13:00:00+00:00
[2023-03-08T16:57:00.103+0000] {standard_task_runner.py:55} INFO - Started process 129 to run task
[2023-03-08T16:57:00.116+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_second_webscrape', 'chatgpt_prediction', 'scheduled__2023-03-07T13:00:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp6lydpvlk']
[2023-03-08T16:57:00.119+0000] {standard_task_runner.py:83} INFO - Job 203: Subtask chatgpt_prediction
[2023-03-08T16:57:00.290+0000] {task_command.py:388} INFO - Running <TaskInstance: bitcoin_second_webscrape.chatgpt_prediction scheduled__2023-03-07T13:00:00+00:00 [running]> on host cd114ba8c1f8
[2023-03-08T16:57:00.410+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin_second_webscrape
AIRFLOW_CTX_TASK_ID=chatgpt_prediction
AIRFLOW_CTX_EXECUTION_DATE=2023-03-07T13:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-07T13:00:00+00:00
[2023-03-08T16:57:00.441+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/openai.py", line 26, in chat_gpt_prediction
    completion = openai.Completion.create(
AttributeError: module 'openai' has no attribute 'Completion'
[2023-03-08T16:57:00.456+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bitcoin_second_webscrape, task_id=chatgpt_prediction, execution_date=20230307T130000, start_date=20230308T165700, end_date=20230308T165700
[2023-03-08T16:57:00.474+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 203 for task chatgpt_prediction (module 'openai' has no attribute 'Completion'; 129)
[2023-03-08T16:57:00.535+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-08T16:57:00.561+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
